spring.application.name=eharvest

#spring.datasource.url=jdbc:postgresql://db:5432/eharvest
spring.datasource.url=jdbc:postgresql://localhost:5432/eharvest
spring.datasource.username=postgres
spring.datasource.password=password

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# application.properties
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE

# External AI API key (Keep this secure in production)
ai.api.key=eharvest-ai-secret-key-12345

# File storage
storage.base-dir=uploads

# Paynow (placeholders)
paynow.integration.id=
paynow.integration.key=
